Add support for dpt 8.xxx
vapourismo/knx-go pull request #91
Opened 2024-08-25 18:50 UTC by pakerfeldt

2024-08-25 18:56 UTC, pakerfeldt commented on knx/dpt/types_8..go
> +// DPT_8004 represents DPT 8.004 / delta time deciseconds
I'm wondering if this is actually correct. Spec seem to suggest that this value should be divided by 10, and DPT_8005 by 100. But it's the same with 7.003 and 7.004 and this library does not seem to treat those in any special way so not sure.

2024-08-26 13:08 UTC, vapourismo requested changes
Thanks for adding these!

I recommend representing the values using the units that KNX defines for these datapoint types.

I am referring to these, in case you don't have them handy:

<img width="568" alt="image" src="https://github.com/user-attachments/assets/a55cbc13-bc17-4ad9-adf2-3b1b0dbb4fa7">

2024-08-26 13:08 UTC, vapourismo commented on knx/dpt/types_8..go
> +	return "cs"
8.003 uses milliseconds, use that instead.

2024-08-26 13:08 UTC, vapourismo commented on knx/dpt/types_8..go
> +	return fmt.Sprintf("%d cs", int16(d))
Change this to milliseconds as well.

2024-08-26 13:08 UTC, vapourismo commented on knx/dpt/types_8..go
> +	return fmt.Sprintf("%d °", int16(d))
```suggestion
	return fmt.Sprintf("%d pulses", int16(d))
```

2024-08-26 13:09 UTC, vapourismo commented on knx/dpt/types_8..go
Please remove the spurious `.` in this file's name.

2024-08-26 18:56 UTC, pakerfeldt commented
> Thanks for adding these!
> 
> I recommend representing the values using the units that KNX defines for these datapoint types.
> 
> I am referring to these, in case you don't have them handy:
> 
> <img alt="image" width="568" src="https://private-user-images.githubusercontent.com/2806669/361442495-a55cbc13-bc17-4ad9-adf2-3b1b0dbb4fa7.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MjQ2OTgxMDQsIm5iZiI6MTcyNDY5NzgwNCwicGF0aCI6Ii8yODA2NjY5LzM2MTQ0MjQ5NS1hNTVjYmMxMy1iYzE3LTRhZDktYWRmMi0zYjFiMGRiYjRmYTcucG5nP1gtQW16LUFsZ29yaXRobT1BV1M0LUhNQUMtU0hBMjU2JlgtQW16LUNyZWRlbnRpYWw9QUtJQVZDT0RZTFNBNTNQUUs0WkElMkYyMDI0MDgyNiUyRnVzLWVhc3QtMSUyRnMzJTJGYXdzNF9yZXF1ZXN0JlgtQW16LURhdGU9MjAyNDA4MjZUMTg0MzI0WiZYLUFtei1FeHBpcmVzPTMwMCZYLUFtei1TaWduYXR1cmU9MDk2YjllZGRkNGU0ZTcyZTg3N2ZkNWEwNmEzMzgxOGRlZWFjZjMxNzc0ZmE1YmUyZDZkYTkwMTk3MjdiODU4ZCZYLUFtei1TaWduZWRIZWFkZXJzPWhvc3QmYWN0b3JfaWQ9MCZrZXlfaWQ9MCZyZXBvX2lkPTAifQ.AcMgD18qhmSoKoc7cGUNacLCZ7ubYcsbEsoqbvjk2aE">

In lack of better source, I was referring to https://www.promotic.eu/en/pmdoc/Subsystems/Comm/PmDrivers/KNXDTypes.htm
<img width="992" alt="image" src="https://github.com/user-attachments/assets/e2645a78-f260-4ba2-8b5c-d3f45c6a733b">
Maybe not the best source but it suggests all 8.xxx are 2 byte integers. This is also how they are represented in for example this javascript library: https://github.com/ekarak/knx/blob/master/src/dptlib/dpt8.js

My interpretation is that they should be unpacked as 2 byte integer and then afterwards, divided by 10 and 100 respectively. If these are unpacked as float directly, will they get the correct value? 🤔

2024-08-26 19:07 UTC, vapourismo commented
> In lack of better source, I was referring to https://www.promotic.eu/en/pmdoc/Subsystems/Comm/PmDrivers/KNXDTypes.htm <img alt="image" width="992" src="https://private-user-images.githubusercontent.com/195860/361539839-e2645a78-f260-4ba2-8b5c-d3f45c6a733b.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MjQ2OTkwMDMsIm5iZiI6MTcyNDY5ODcwMywicGF0aCI6Ii8xOTU4NjAvMzYxNTM5ODM5LWUyNjQ1YTc4LWYyNjAtNGJhMi04YjVjLWQzZjQ1YzZhNzMzYi5wbmc_WC1BbXotQWxnb3JpdGhtPUFXUzQtSE1BQy1TSEEyNTYmWC1BbXotQ3JlZGVudGlhbD1BS0lBVkNPRFlMU0E1M1BRSzRaQSUyRjIwMjQwODI2JTJGdXMtZWFzdC0xJTJGczMlMkZhd3M0X3JlcXVlc3QmWC1BbXotRGF0ZT0yMDI0MDgyNlQxODU4MjNaJlgtQW16LUV4cGlyZXM9MzAwJlgtQW16LVNpZ25hdHVyZT1hZTVkNDgxNjcxZjlmNTIwZGNlZDY5ZTMzYmVkYjhhNGY1Nzg2YTgzMjM1MWY1YTZlOWMyNWYyODQ5OTU1MzgwJlgtQW16LVNpZ25lZEhlYWRlcnM9aG9zdCZhY3Rvcl9pZD0wJmtleV9pZD0wJnJlcG9faWQ9MCJ9.8NpZGampsByRHOjZhTN5dZ6YMaCQnIPS0uoCOgZVnyk"> Maybe not the best source but it suggests all 8.xxx are 2 byte integers. This is also how they are represented in for example this javascript library: https://github.com/ekarak/knx/blob/master/src/dptlib/dpt8.js
> 
> My interpretation is that they should be unpacked as 2 byte integer and then afterwards, divided by 10 and 100 respectively. If these are unpacked as float directly, will they get the correct value? 🤔

I think I see where where the confusion lies. There is a representation within the KNX payload where all DPT 8.xxx are indeed represented as a 16-bit signed integers. However, this library interprets the KNX payload as the respective DPT (ideally with correct units).

2024-08-26 19:10 UTC, pakerfeldt commented on knx/dpt/types_8..go
> +// DPT_8004 represents DPT 8.004 / delta time deciseconds
Both of them are actually in seconds. But by calling the units centiseconds and deciseconds we combat the need for dividing them by 100 and 10 respectively. That's why I used those units.

2024-08-26 19:16 UTC, pakerfeldt commented
> I think I see where where the confusion lies. There is a representation within the KNX payload where all DPT 8.xxx are indeed represented as a 16-bit signed integers. However, this library interprets the KNX payload as the respective DPT (ideally with correct units).

My point is that `ms` would not be the correct unit unless this library also provides the resolution of the DPT. I would suggest this library gives the correct unit after applying the resolution. WDYT?

2024-08-26 19:35 UTC, pakerfeldt commented
I see two options. Return the int16 values with units centiseconds and deciseconds. This is what my PR essentially does but I agree those units are not common, albeit indeed a valid unit.

Or alternatively, decode as int16 and only afterwards divide by 10 or 100 and report unit as seconds.

Haven’t checked but float32 would likely not yield correct values. 🤔

2024-08-27 06:21 UTC, pakerfeldt commented
I think I can create alternative pack/unpack functions to support this. I'll get back with a change that you can review.

2024-08-27 10:10 UTC, pakerfeldt commented on knx/dpt/types_8.go
> +// DPT_8003 represents DPT 8.003 / delta time seconds with two decimal places
I was checking ETS and noticed it does present the values in `ms`, but then again, it would require some changes to the pack/unpack. 🤔

2024-08-27 12:55 UTC, pakerfeldt commented
Closing this in favour of #93

2024-08-27 12:55 UTC, closed without merging